services:
  postgres:
    image: 'postgres:16.2-alpine3.19'
    container_name: 'skeleton-postgres'
    environment:
      - 'POSTGRES_DB=local_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user'
    ports:
      - '15432:5432'
  rabbitmq:
    image: 'rabbitmq:3.13-management-alpine'
    container_name: 'skeleton-rabbitmq'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=user'
    ports:
      - '35672:5672'
      - '15672:15672'
  redis:
    container_name: 'skeleton-redis'
    image: "redis/redis-stack:7.2.0-v9"
    environment:
      - 'REDIS_ARGS= --save 20 1 --requirepass secret'
    ports:
      - "18001:8001"
      - "16379:6379"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
