services:
  postgres:
    image: 'postgres:16.2-alpine3.19'
    container_name: 'skeleton-postgres'
    environment:
      - 'POSTGRES_DB=local_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user'
    ports:
      - '15432:5432'
  rabbitmq:
    image: 'rabbitmq:3.13-management-alpine'
    container_name: 'skeleton-rabbitmq'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=user'
    ports:
      - '35672:5672'
      - '15672:15672'
